"""
Django settings for dstore project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kq4we8i^(uh#rw=u!v!m__ok#ft(z_ai^d3e3z2q*i#f=6xk1d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
AUTH_USER_MODEL='users.CustomUser'
#########add ip 192.168.1.105
ALLOWED_HOSTS = ['127.0.0.1','localhost:3000','store.local','192.168.1.100','store.pythone.local','192.168.1.105']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ####################
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'files',
    'products',
    'carts',
    'orders',
]
# تنظیم JWT در DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
# تنظیمات JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # عمر توکن دسترسی
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # عمر توکن رفرش
    'ROTATE_REFRESH_TOKENS': True,  # چرخش توکن‌های رفرش
    'BLACKLIST_AFTER_ROTATION': True,  # اضافه کردن به لیست سیاه بعد از چرخش
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # کلید امضا برای توکن‌ها
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    ###########
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ############
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'store.local.python',  # نام دیتابیس شما
        'USER': 'root',       # نام کاربری MySQL
        'PASSWORD': '',   # رمز عبور MySQL
        'HOST': '127.0.0.1',           # آدرس سرور دیتابیس (در صورت نیاز به استفاده از سرورهای راه دور، آدرس صحیح وارد شود)
        'PORT': '3306',                # پورت MySQL (پورت پیش‌فرض MySQL 3306 است)
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'store_local_python',  # نام دیتابیس شما
        'USER': 'root',       # نام کاربری MySQL
        'PASSWORD': 'ame@6558U',   # رمز عبور MySQL
        'HOST': '127.0.0.1',           # آدرس سرور دیتابیس (در صورت نیاز به استفاده از سرورهای راه دور، آدرس صحیح وارد شود)
        'PORT': '3306',                # پورت MySQL (پورت پیش‌فرض MySQL 3306 است)
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#############
###در اینجا درخواسن ها فقط از دامنه های مجاز هستش
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # آدرس frontend شما
    'http://127.0.0.1:3000',
    'http://192.168.1.100',
    'http://store.local',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_BLACKLIST_ENABLED': True,  # این خط برای فعال کردن بلک‌لیست
}

#for media
import os
#STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


###################  Setting Celery For Queue ############3
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'


############################  Add Logger ###########
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            #'filename': 'django_debug.log',
            ######add /var/www/store/public_html/dstore/django_debug.log
            'filename':'/var/www/store/public_html/dstore/django_debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        '__main__': {  # برای لاگ‌های شخصی‌سازی شده
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

