# Generated by Django 3.2.25 on 2024-10-20 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('files', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='products.category'),
        ),
        migrations.AddField(
            model_name='file',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='products.product'),
        ),
    ]
