# Generated by Django 3.2.25 on 2024-10-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20241025_1915'),
        ('files', '0003_auto_20241020_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shippingMethod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='orders.shippingmethod'),
        ),
    ]
