# Generated by Django 3.2.25 on 2024-10-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_invoice_shipping_cost'),
        ('files', '0004_file_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='paymentMethod',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='orders.paymentmethod'),
        ),
    ]
