# Generated by Django 3.2.25 on 2024-10-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_paymentgateway'),
        ('files', '0005_file_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='paymentGateway',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='orders.paymentgateway'),
        ),
    ]
