# Generated by Django 3.2.25 on 2024-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
