# Generated by Django 3.2.25 on 2024-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20241025_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='estimated_delivery_time',
            new_name='delivery_time',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
