# Generated by Django 3.2.25 on 2024-10-27 16:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
