# Generated by Django 3.2.25 on 2024-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_invoice_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
