# Generated by Django 3.2.25 on 2024-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_paymentmethod_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terminal_id', models.CharField(max_length=100, unique=True)),
                ('wsdl', models.TextField(blank=True, null=True)),
                ('wsdl_confirm', models.CharField(blank=True, max_length=255, null=True)),
                ('wsdl_reverse', models.CharField(blank=True, max_length=255, null=True)),
                ('wsdl_multiplexed', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_gateway', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gateway Payment',
                'verbose_name_plural': 'Gateway Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
